spring.application.name=backend
server.port=4000

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:tiendadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret
jwt.secret=7d8251e9411d4e0e84b80b2a758ec531c36ef27a1c1d91a92e10c1287f3db1a4c95f190e4811a21e4281f69202167d4e414c53ef8211b5e39669527f311c6d3
jwt.expiration=86400000
